doctrine_migrations:
  migrations_paths:
    # Migrations pour Entity Manager 'app' (MySQL)
    'DoctrineMigrations\App': '%kernel.project_dir%/migrations/App'
    # Migrations pour Entity Manager 'rag' (PostgreSQL)
    'DoctrineMigrations\Rag': '%kernel.project_dir%/migrations/Rag'

  storage:
    table_storage:
      table_name: 'doctrine_migration_versions'

  enable_profiler: false