settings:
  analysis:
    normalizer:
      lowercase_normalizer:
        type: custom
        char_filter: []
        filter:
          - lowercase
          - asciifolding  # Supprime les accents
  # Optimisations pour l'indexation en masse
  refresh_interval: "30s"
  number_of_replicas: 0
  max_result_window: 50000

mappings:
  dynamic: false
  properties:
    # Identifiants et références
    caseId:
      type: integer
    caseReference:
      type: keyword  # Recherche exacte pour les références
      fields:
        normalized:
          type: keyword
          normalizer: lowercase_normalizer
    caseShortReference:
      type: keyword
      fields:
        normalized:
          type: keyword
          normalizer: lowercase_normalizer

    # Informations générales du dossier
    caseTitle:
      type: text
      fields:
        keyword:
          type: keyword  # Pour tri et filtre exact
        normalized:
          type: keyword
          normalizer: lowercase_normalizer
    caseAgency:
      type: text
      fields:
        keyword:
          type: keyword
        normalized:
          type: keyword
          normalizer: lowercase_normalizer
    caseClient:
      type: text
      fields:
        keyword:
          type: keyword
        normalized:
          type: keyword
          normalizer: lowercase_normalizer
    caseStatus:
      type: keyword  # Status = filtre exact
      fields:
        normalized:
          type: keyword
          normalizer: lowercase_normalizer
    caseManager:
      type: text
      fields:
        keyword:
          type: keyword
        normalized:
          type: keyword
          normalizer: lowercase_normalizer

    # Métriques calculées pour optimiser les requêtes
    reportsCount:
      type: integer
    reviewsCount:
      type: integer
    hasReports:
      type: boolean
    hasReviews:
      type: boolean
    hasObservations:
      type: boolean

    # Données textuelles pour la recherche globale
    searchableText:
      type: text
      fields:
        suggest:
          type: completion
          analyzer: simple

    # Structure hiérarchique des rapports (nested)
    reports:
      type: nested
      properties:
        reportId:
          type: integer
        reportReference:
          type: keyword
          fields:
            normalized:
              type: keyword
              normalizer: lowercase_normalizer
        reportImported:
          type: boolean
        reportIsDraft:
          type: boolean
        reportIsValidated:
          type: boolean
        reportCreatedAt:
          type: date
          format: "yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd HH:mm:ss"
        reportValidatedAt:
          type: date
          format: "yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd HH:mm:ss"

        reportTypeName:
          type: text
          fields:
            keyword:
              type: keyword
            normalized:
              type: keyword
              normalizer: lowercase_normalizer
        reportTypeCode:
          type: keyword
        reportS3Path:
          type: keyword
          index: false  # Pas indexé car utilisé uniquement pour le téléchargement

        # Métriques par rapport
        reportReviewsCount:
          type: integer
        reportHasReviews:
          type: boolean

        # Structure des avis (nested dans nested)
        reportReviews:
          type: nested
          properties:
            reviewId:
              type: integer
            reviewNumber:
              type: keyword
            reviewObservation:
              type: text
              fields:
                keyword:
                  type: keyword
                  ignore_above: 2000  # Limite pour éviter les erreurs
            reviewCreatedBy:
              type: text
              fields:
                keyword:
                  type: keyword
            reviewPosition:
              type: integer
            reviewVisitedAt:
              type: date
              format: "yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd HH:mm:ss"
            reviewCreatedAt:
              type: date
              format: "yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd HH:mm:ss"
            reviewDomain:
              type: keyword
              fields:
                normalized:
                  type: keyword
                  normalizer: lowercase_normalizer
            reviewValueCode:
              type: keyword
              fields:
                normalized:
                  type: keyword
                  normalizer: lowercase_normalizer
            reviewValueName:
              type: keyword
              fields:
                normalized:
                  type: keyword
                  normalizer: lowercase_normalizer
    # Métadonnées de traitement
    indexedAt:
      type: date
      format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
    processingMode:
      type: keyword
